# action.yml
name: Deploy to surge.sh
description: deploy your static site to surge.sh
inputs:
    folder:
        description: The folder the action should deploy
        required: true
        default: .
    domain:
        description: Your domain or use surge.sh provided
        required: true
    token:
        description: The SURGE_TOKEN
        required: true
runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.folder }}
        - ${{ inputs.domain }}
        - ${{ inputs.token }}
