# action.yml
name: "Deploy to surge.sh"
description: "deploy your static site to surge.sh"
inputs:
    folder:
        required: true
        default: "."
    domain:
        required: true
    token:
        required: true
runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.folder }}
        - ${{ inputs.domain }}
        - ${{ inputs.token }}
